import Head from 'next/head'

import DoingSectionCardContainer from '../containers/Card/SectionCard/DoingSectionCardContainer';
import DoneSectionCardContainer from '../containers/Card/SectionCard/DoneSectionCardContainer';
import NoneSectionCardContainer from '../containers/Card/SectionCard/NoneSectionCardContainer';
import TopNavContainer from '../containers/Nav/TopNavContainer';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col h-screen'>
        <div className='h-16 px-8'>
          <TopNavContainer />
        </div>
        <div className='flex gap-8 h-[calc(100%-4rem)] p-8'>
          <NoneSectionCardContainer />
          <DoingSectionCardContainer />
          <DoneSectionCardContainer />
        </div>
      </div>
    </div>
  )
}
