import Head from 'next/head'

import DoingSectionCardContainer from '../containers/Card/SectionCard/DoingSectionCardContainer';
import DoneSectionCardContainer from '../containers/Card/SectionCard/DoneSectionCardContainer';
import NoneSectionCardContainer from '../containers/Card/SectionCard/NoneSectionCardContainer';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex gap-8 h-screen p-8'>
        <NoneSectionCardContainer />
        <DoingSectionCardContainer />
        <DoneSectionCardContainer />
      </div>
    </div>
  )
}
