import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import Head from 'next/head'

import { RootState, useAppDispatch } from '../store/store';
import { increment, decrement } from '../store/reducers/sample'

export default function Home() {
  const dispatch = useAppDispatch();
  const { count } = useSelector((state: RootState) => state.sample);

  function addCount() {
    dispatch(increment(2))
  }
  function minusCount() {
    dispatch(decrement(3))
  }

  useEffect(() => {
    console.log('COUNT =', count)
  }, [count])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <input type="text" value={count} />
      </div>
      <button onClick={addCount}>+</button>
      <button onClick={minusCount}>-</button>
    </div>
  )
}
